stdout of test 'tst304` in directory 'src/mal` itself:
# Monet Database Server V5.0
# Copyright (c) 1993-2004, CWI. All rights reserved.
# compiled for 32biti686-pc-linux-gnu/32bit.
# config:/ufs/mk/monet5/src/mal/Tests/tst.conf
# dbfarm:/ufs/mk/monet5/Linux/var/MonetDB/dbfarm
# dbname:demo
# Visit http://monetdb.cwi.nl for further information.
## Exceptions can be explicitly raised in a function
## which requires the exception identifier to be defined.
#
#function myException();
#raise	IllegalAccess:="new exception";
#	print("should have left function ");
#end myException;
function Admin.myException():void;	# 0  (myException:void)
    raise IllegalAccess := "new exception";	# 1  (IllegalAccess:str)<-($2:str)
    io.print("should have left function ");	# 2 IOprint_val ($3:int)<-($4:str)
end myException;	# 3  
#
#	myException();
#	print("should not come here");
##exception block;
#catch	IllegalAccess;
#	printf("catched IllegalAccess\n");
#exit	IllegalAccess;
#	print("done");
#
function Admin.main():int;	# 0  (main:int)
    Admin.myException();	# 1  ($1:void)
    io.print("should not come here");	# 2 IOprint_val ($2:int)<-($3:str)
catch IllegalAccess;	# 3  (IllegalAccess:any) jump 5
    io.printf("catched IllegalAccess\n");	# 4 IOprint_str ($5:int)<-($6:str)
exit IllegalAccess;	# 5  (IllegalAccess:any)
    io.print("done");	# 6 IOprint_val ($7:int)<-($8:str)
end main;	# 7  
!ERROR: new exceptionMALexception:Admin.myException[3]: propagated
>