stdout of test 'tst607` in directory 'src/mal` itself:


# 08:01:25 >  
# 08:01:25 >  Mtimeout -timeout 60 Mserver "--config=/ufs/mk/monet5/Linux/etc/MonetDB5.conf" --debug=10 --set "monet_mod_path=/ufs/mk/monet5/Linux/lib/MonetDB5:/ufs/mk/opensource/MonetDB/Linux/lib/MonetDB" --set "gdk_dbfarm=/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm" --set "sql_logdir=/ufs/mk/monet5/Linux/var/MonetDB5/log" --set mapi_port=42158 --set sql_port=55708 --set monet_prompt= --trace "--config=/ufs/mk/monet5/src/mal/Tests/All.conf" --dbname=mTests_src_mal  tst607.mal </dev/null
# 08:01:25 >  

# Monet Database Server V4.99.19
# Copyright (c) 1993-2004, CWI. All rights reserved.
# Compiled for i686-redhat-linux-gnu/32bit; dynamically linked.
# config:/ufs/mk/monet5/Linux/etc/MonetDB5.conf
# dbfarm:/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm
# dbname:mTests_src_mal
# Visit http://monetdb.cwi.nl/ for further information.
## using spaces
#
#u:str:=const.take(user);
#printf("User bound to %s\n",u);
#roomnumber:= 321;
#const.deposit(roomnumber);
#
#v:int:= const.take(roomnumber);
#print(v);
#v:= 123;
#v:= v+1;
#const.release(roomnumber);
#print("attempt twice to release");
#const.release(roomnumber); # failure? done twice or implicit take?
#
function user.main():int;	# 0  (main:int)
# using spaces 	# 1  ($2:str)
    u := const.take("user");	# 2 CSTtake (u:str)<-($4:str)
    io.printf("User bound to %s\n",u);	# 3 IOprint_formatted_str ($5:int)<-($6:str)(u:str)
    roomnumber := 321;	# 4  (roomnumber:int)<-($8:int)
    const.deposit("roomnumber",roomnumber);	# 5 CSTdeposit ($9:void)<-($10:str)(roomnumber:int)
    v := const.take("roomnumber");	# 6 CSTtake (v:int)<-($10:str)
    io.print(v);	# 7 IOprint_val ($12:int)<-(v:int)
    v := 123;	# 8  (v:int)<-($13:int)
    v := calc.+(v,1);	# 9 CALCbinaryADDintint (v:int)<-(v:int)($14:int)
    const.release("roomnumber");	# 10 CSTrelease ($15:void)<-($10:str)
    io.print("attempt twice to release");	# 11 IOprint_val ($16:int)<-($17:str)
    const.release("roomnumber");	# 12 CSTrelease ($18:void)<-($10:str)
# failure? done twice or implicit take? 	# 13  ($20:str)
end main;	# 14  
User bound to user
[ 321 ]
[ "attempt twice to release" ]

# 08:01:25 >  
# 08:01:25 >  Done.
# 08:01:25 >  

